package com.mds2.d100.foro.ventana;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed, e.g
 * class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Agregar_multimedia_ventana extends VerticalLayout {
	protected HorizontalLayout iniciar_sesion_superior;
	protected VerticalLayout iniciar_sesion_mitad;
	protected TextField text_agregar_video;
	protected PasswordField text_agregar_imagen1;
	protected PasswordField text_agregar_imagen2;
	protected PasswordField text_agregar_imagen3;
	protected Button boton_agregar_aceptar;
	protected HorizontalLayout iniciar_sesion_inferior;

	public Agregar_multimedia_ventana() {
		Design.read(this);
	}
}
