package com.mds2.d100.foro.ventana;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed, e.g
 * class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Cabecera_ventana extends VerticalLayout {
	protected Button boton_logo;
	protected GridLayout cabecera_usuario_nr;
	protected Button boton_iniciar_sesion;
	protected Button boton_registrarse;
	protected GridLayout cabecera_usuario_r;
	protected Label label_cabecera_nombre;
	protected Button boton_funciones;

	public Cabecera_ventana() {
		Design.read(this);
	}
}
