package com.mds2.d100.foro.ventana;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed, e.g
 * class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Crear_seccion_ventana extends VerticalLayout {
	protected HorizontalLayout crear_seccion_sup;
	protected VerticalLayout crear_seccion_mid;
	protected TextField text_crear_seccion_nombre;
	protected NativeSelect<java.lang.String> selector_crear_seccion_visibilidad;
	protected TextArea text_crear_seccion_descripcion;
	protected Button boton_crear_seccion_cancelar;
	protected Button boton_crear_seccion_aceptar;
	protected HorizontalLayout crear_seccion_inf;

	public Crear_seccion_ventana() {
		Design.read(this);
	}
}
