package com.mds2.d100.foro.ventana;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed, e.g
 * class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Funciones_comunes_ventana extends VerticalLayout {
	protected VerticalLayout funciones_administrador_botones;
	protected VerticalLayout funciones_comunes_botones;
	protected Button boton_mi_perfil;
	protected Button boton_mis_notificaciones;
	protected Button boton_cerrar_sesion;
	protected Button boton_tema_rosa;
	protected Button boton_tema_verde;
	protected Button boton_tema_naranja;
	protected Button boton_tema_amarillo;
	protected VerticalLayout funciones_admin;
	protected Button boton_usuarios_restringidos;
	protected Button boton_crear_seccion;
	protected TextField text_funciones_comunes_mensajes;

	public Funciones_comunes_ventana() {
		Design.read(this);
	}
}
