package com.mds2.d100.foro.ventana;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed, e.g
 * class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Interfaz_ventana extends VerticalLayout {
	protected HorizontalLayout interfaz_cabecera;
	protected HorizontalLayout interfaz_inferior;
	protected HorizontalLayout interfaz_panel_izq;
	protected VerticalLayout interfaz_panel_central;
	protected HorizontalLayout interfaz_panel_derecho;

	public Interfaz_ventana() {
		Design.read(this);
	}
}
