package com.mds2.d100.foro.ventana;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed, e.g
 * class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Mensaje_ventana extends VerticalLayout {
	protected Button boton_mensaje_foto_perfil;
	protected Label label_mensaje_nombre;
	protected Label label_mensaje_descripcion;
	protected HorizontalLayout boton_mensaje_responder1;
	protected Button boton_mensaje_responder;
	protected Button borrar_mensaje;
	protected Button boton_reportar_mensaje;
	protected Button boton_gusta_mensaje;
	protected Label label_mensaje_fecha;

	public Mensaje_ventana() {
		Design.read(this);
	}
}
