package com.mds2.d100.foro.ventana;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed, e.g
 * class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Modificar_perfil_ventana extends VerticalLayout {
	protected HorizontalLayout mod_perfil_sup;
	protected VerticalLayout mod_perfil_mid;
	protected Image image_modificar_perfil;
	protected Label label_modificar_perfil_nombre;
	protected TextArea text_modificar_perfil_descripcion;
	protected TextField text_modificar_perfil_nombre;
	protected Button boton_modificar_perfil_eliminar;
	protected Button boton_modificar_perfil_guardar;
	protected HorizontalLayout mod_perfil_inf;

	public Modificar_perfil_ventana() {
		Design.read(this);
	}
}
