package com.mds2.d100.foro.ventana;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed, e.g
 * class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Modificar_tema_ventana extends VerticalLayout {
	protected HorizontalLayout mod_tema_sup;
	protected VerticalLayout mod_tema_mid;
	protected Button boton_modificar_tema_eliminar;
	protected TextField text_modificar_tema_nomobre;
	protected NativeSelect<java.lang.String> select_modificar_tema_visibilidad;
	protected TextArea text_modificar_tema_descripcion;
	protected Button boton_modificar_tema_icono1;
	protected Button boton_modificar_tema_icono2;
	protected Button boton_modificar_tema_icono3;
	protected Button boton_modificar_tema_icon4;
	protected Button boton_modificar_tema_icono5;
	protected Button boton_modificar_tema_icono6;
	protected Button boton_modificar_tema_cancelar;
	protected Button boton_modificar_tema_icono_aceptar;
	protected HorizontalLayout mod_tema_inf;

	public Modificar_tema_ventana() {
		Design.read(this);
	}
}
