package com.mds2.d100.foro.ventana;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed, e.g
 * class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Notificacion_ventana extends HorizontalLayout {
	protected Label label_notificacion_icono;
	protected Label label_notificacion_titulo;
	protected Label label_notificacion_contenido;
	protected Label label_notificacion_fecha;

	public Notificacion_ventana() {
		Design.read(this);
	}
}
