package com.mds2.d100.foro.ventana;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed, e.g
 * class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Panel_de_mensajes_ventana extends VerticalLayout {
	protected Label label_panel_de_mensajes_titulo;
	protected Button panel_de_mensajes_mod;
	protected Button panel_de_mensajes_like;
	protected Button panel_de_mensajes_report;
	protected Image image_panel_de_mensajes;
	protected Label label_panel_de_mensajes_nombre;
	protected Label label_panel_de_mensajes_fecha;
	protected Label label_panel_de_mensajes_contenido;
	protected GridLayout grid_panel_mensajes;
	protected HorizontalLayout panel_enviar_mensaje;
	protected TextField text_mensaje;
	protected Button boton_mensaje_multimedia;
	protected Button boton_mensaje_enviar;

	public Panel_de_mensajes_ventana() {
		Design.read(this);
	}
}
