package com.mds2.d100.foro.ventana;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed, e.g
 * class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Panel_derecho_ventana extends VerticalLayout {
	protected VerticalLayout panel_derecho_desconectado;
	protected VerticalLayout panel_derecho_conectado;
	protected GridLayout grid_panel_derecho_amigos;

	public Panel_derecho_ventana() {
		Design.read(this);
	}
}
