package com.mds2.d100.foro.ventana;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed, e.g
 * class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Perfil_ventana extends VerticalLayout {
	protected HorizontalLayout perfil_info;
	protected Image image_perfil;
	protected Label label_perfil_usuario;
	protected Label label_perfil_descripcion;
	protected Button boton_perfil_restringir;
	protected Button boton_perfil_amigo;
	protected Button boton_perfil_notificar;
	protected Button boton_perfil_ascender;
	protected TabSheet tab_perfil_usuario;
	protected GridLayout grid_perfil_amigos;
	protected GridLayout grid_perfil_contribuciones;
	protected VerticalLayout grid_perfil_modificar;
	protected TextField text_nombre;
	protected TextArea text_descripcion;

	public Perfil_ventana() {
		Design.read(this);
	}
}
