package org.ual.hmis.d100; // Generated by Selenium IDE

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;

import org.openqa.selenium.interactions.Actions;

@SuppressWarnings("unused")
public class LogindeusuarioincorrectoTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		 // System.setProperty("webdriver.gecko.driver", "drivers/geckodriver.exe");
		 // System.setProperty("webdriver.chrome.driver", "drivers/chromedriver.exe");
		FirefoxOptions firefoxOptions = new FirefoxOptions();
		firefoxOptions.setHeadless(true);
		driver = new FirefoxDriver(firefoxOptions); // new ChromeDriver(chromeOptions); // new
													// ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void logindeusuarioincorrecto() {
		driver.get("https://hmis.azurewebsites.net/");
		driver.manage().window().setSize(new Dimension(839, 555));
		driver.findElement(By.linkText("Login")).click();
		driver.findElement(By.id("login-submit")).click();
		assertThat(driver.findElement(By.cssSelector(".text-danger li:nth-child(1)")).getText(),
				is("The Email field is required."));
		assertThat(driver.findElement(By.cssSelector(".text-danger li:nth-child(2)")).getText(),
				is("The Password field is required."));
		driver.findElement(By.id("Input_Email")).click();
		driver.findElement(By.id("Input_Email")).sendKeys("qer");
		{
			WebElement element = driver.findElement(By.id("Input_Email-error"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).release().perform();
		}
		assertThat(driver.findElement(By.id("Input_Email-error")).getText(),
				is("The Email field is not a valid e-mail address."));
		driver.findElement(By.id("Input_Email")).click();
		driver.findElement(By.cssSelector(".form-group:nth-child(4)")).click();
		driver.findElement(By.id("Input_Email")).click();
		driver.findElement(By.id("Input_Email")).sendKeys("a@a.com");
		driver.findElement(By.id("Input_Password")).click();
		driver.findElement(By.cssSelector(".col-md-6")).click();
		driver.findElement(By.id("Input_Password")).click();
		driver.findElement(By.id("Input_Password")).sendKeys("invalido");
		driver.findElement(By.cssSelector("body")).click();
		driver.findElement(By.id("login-submit")).click();
		assertThat(driver.findElement(By.cssSelector(".text-danger li")).getText(), is("Invalid login attempt."));
	}
}
