package org.ual.hmis.d100; // Generated by Selenium IDE

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;

import org.openqa.selenium.interactions.Actions;

@SuppressWarnings("unused")
public class RegistrodeusuarioincorrectoTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		 // System.setProperty("webdriver.gecko.driver", "drivers/geckodriver.exe");
		 // System.setProperty("webdriver.chrome.driver", "drivers/chromedriver.exe");
		FirefoxOptions firefoxOptions = new FirefoxOptions();
		firefoxOptions.setHeadless(true);
		driver = new FirefoxDriver(firefoxOptions); // new ChromeDriver(chromeOptions); // new
													// ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void registrodeusuarioincorrecto() {
		driver.get("https://hmis.azurewebsites.net/");
		driver.manage().window().setSize(new Dimension(837, 553));
		driver.findElement(By.linkText("Register")).click();
		assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Register"));
		driver.findElement(By.id("Input_Email")).click();
		driver.findElement(By.id("Input_Email")).sendKeys("qwerty");
		{
			WebElement element = driver.findElement(By.cssSelector(".form-group:nth-child(5)"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).clickAndHold().perform();
		}
		{
			WebElement element = driver.findElement(By.cssSelector(".form-group:nth-child(4)"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).release().perform();
		}
		driver.findElement(By.id("registerForm")).click();
		assertThat(driver.findElement(By.id("Input_Email-error")).getText(),
				is("The Email field is not a valid e-mail address."));
		driver.findElement(By.id("Input_Password")).click();
		driver.findElement(By.id("Input_Password")).clear();
		driver.findElement(By.id("Input_Password")).sendKeys("easy");
		driver.findElement(By.id("registerForm")).click();
		assertThat(driver.findElement(By.id("Input_Password-error")).getText(),
				is("The Password must be at least 6 and at max 100 characters long."));
		driver.findElement(By.id("Input_Password")).click();
		driver.findElement(By.id("Input_Password")).clear();
		driver.findElement(By.id("Input_Password")).sendKeys("veryeasy");
		driver.findElement(By.cssSelector(".form-group:nth-child(6)")).click();
		driver.findElement(By.id("Input_ConfirmPassword")).click();
		driver.findElement(By.id("Input_ConfirmPassword")).clear();
		driver.findElement(By.id("Input_ConfirmPassword")).sendKeys("no coincide");
		driver.findElement(By.cssSelector(".col-md-6")).click();
		assertThat(driver.findElement(By.id("Input_ConfirmPassword-error")).getText(),
				is("The password and confirmation password do not match."));
		driver.findElement(By.id("Input_ConfirmPassword")).click();
		driver.findElement(By.id("Input_ConfirmPassword")).click();
		{
			WebElement element = driver.findElement(By.id("Input_ConfirmPassword"));
			Actions builder = new Actions(driver);
			builder.doubleClick(element).perform();
		}
		driver.findElement(By.id("Input_ConfirmPassword")).clear();
		driver.findElement(By.id("Input_ConfirmPassword")).sendKeys("veryeasy");
		driver.findElement(By.cssSelector(".col-md-6")).click();
		driver.findElement(By.id("Input_Email")).click();
		driver.findElement(By.id("Input_Email")).click();
		{
			WebElement element = driver.findElement(By.id("Input_Email"));
			Actions builder = new Actions(driver);
			builder.doubleClick(element).perform();
		}
		driver.findElement(By.id("Input_Email")).click();
		driver.findElement(By.id("Input_Email")).click();
		driver.findElement(By.id("Input_Email")).click();
		{
			WebElement element = driver.findElement(By.id("Input_Email"));
			Actions builder = new Actions(driver);
			builder.doubleClick(element).perform();
		}
		driver.findElement(By.cssSelector(".form-group:nth-child(4)")).click();
		driver.findElement(By.id("Input_Email")).click();
		driver.findElement(By.id("Input_Email")).click();
		{
			WebElement element = driver.findElement(By.id("Input_Email"));
			Actions builder = new Actions(driver);
			builder.doubleClick(element).perform();
		}
		driver.findElement(By.id("Input_Email")).clear();
		driver.findElement(By.id("Input_Email")).sendKeys("felipe.antonio.1997@gmail.com");
		driver.findElement(By.cssSelector(".col-md-6")).click();
		driver.findElement(By.id("registerSubmit")).click();
		assertThat(driver.findElement(By.cssSelector(".text-danger li:nth-child(1)")).getText(),
				is("Passwords must have at least one non alphanumeric character."));
		assertThat(driver.findElement(By.cssSelector(".text-danger li:nth-child(2)")).getText(),
				is("Passwords must have at least one digit (\'0\'-\'9\')."));
		driver.findElement(By.cssSelector("li:nth-child(3)")).click();
		driver.findElement(By.cssSelector("li:nth-child(3)")).click();
		driver.findElement(By.cssSelector("li:nth-child(3)")).click();
		assertThat(driver.findElement(By.cssSelector("li:nth-child(3)")).getText(),
				is("Passwords must have at least one uppercase (\'A\'-\'Z\')."));
	}
}
